In [8]:

import pandas, numpy

In [2]:
a = np.arange(12)
b = a.reshape((3,4))

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
def mycrap(x, y =2):
    return x + y

print(mycrap(3**2))

11


In [7]:
total = []

a = [1]
b = [1,2,3]
min_len = min(len(a), len(b))

for i in range(min_len):
    total.append(a[i] + b[i])

print(total)

[2]


In [9]:
int(input("asdsa"))

ValueError: invalid literal for int() with base 10: 'a'